stages:
  - test
  - docker_build
test:
  image: "python:2.7"
  stage: test
  script:
    - make deps
    - PYTHONPATH=. py.test --verbose -s
  docker:
    image: docker:stable
    services:
      - docker:dind
    stage: docker_build
    script:
      - apk add --update make
      - make docker_build
