language: python
python:
  - "2.7"
services:
  - docker
install:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
  - sleep 3; make_test_api
  - sleep 3; make_test_api
  - sleep 3; make_test_api
after_success:
  -make docker_push
