language: python
python:
  - "2.7"
services:
  - docker
install:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
  - make test_xunit
deploy:
  provider: heroku
  app: obscure-journey-46449
  api_key: ${HEROKU_API_KEY}
